---

- name: Set httpd ssl conf SSLCertificateFile
  lineinfile:
    dest: "/etc/httpd/conf.d/ssl.conf"
    state: present
    regexp: "^SSLCertificateFile /"
    line: "SSLCertificateFile {{ ssl_certificate_file }}"

- name: Set httpd ssl conf SSLCertificateKeyFile
  lineinfile:
    dest: "/etc/httpd/conf.d/ssl.conf"
    state: present
    regexp: "^SSLCertificateKeyFile /"
    line: "SSLCertificateKeyFile {{ ssl_certificate_key_file }}"

- name: Set httpd ssl conf SSLCACertificateFile
  lineinfile:
    dest: "/etc/httpd/conf.d/ssl.conf"
    state: present
    regexp: "^#?SSLCACertificateFile /"
    line: "SSLCACertificateFile {{ ssl_ca_certificate_file }}"

- name: Restart httpd
  service: name=httpd state=restarted enabled=yes
