- name: Copy Postgres host based authentication configuration {{ db_data_path }}/pg_hba.conf
  template: src=files/configs/postgresql/pg_hba.conf dest={{ db_data_path }}/pg_hba.conf owner=postgres group=postgres
